# Generated by Django 3.2.5 on 2021-08-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000000)),
                ('email', models.EmailField(max_length=1000000)),
                ('curr_bal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000000)),
                ('email', models.EmailField(max_length=10000000)),
                ('deb_amt', models.IntegerField()),
                ('cr_amt', models.IntegerField()),
                ('acc_bal', models.IntegerField()),
            ],
        ),
    ]
